load("@io_bazel_rules_scala//scala:scala.bzl", "scala_specs2_junit_test")

scala_specs2_junit_test(
    suffixes = ["Test"],
    name = "mod_a",
    srcs = [
        "SampleTest.scala",
        ],
    visibility = ["//visibility:public"],
    deps = [

    ]
)
