load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_binary")

scala_library(
    name = "mod_a",
    srcs = [
        "ModuleA.scala",
        ],
    visibility = ["//visibility:public"],
    deps = [ ]
)